const GET_GROUPS = 'GROUPS/GET_GROUPS';
const SET_GROUPS = `GROUPS/SET_GROUPS`;
const GET_GROUPS_FAILED = `GROUPS/GET_GROUPS_FAILED`;
const CREATE_GROUP = 'GROUPS/CREATE_GROUP';
const CREATE_GROUP_SUCCESS = `GROUPS/CREATE_GROUP_SUCCESS`;
const CREATE_GROUP_FAILED = `GROUPS/CREATE_GROUP_FAILED`;
const UPDATE_GROUP = 'GROUPS/UPDATE_GROUP';
const UPDATE_GROUP_SUCCESS = `GROUPS/UPDATE_GROUP_SUCCESS`;
const UPDATE_GROUP_FAILED = `GROUPS/UPDATE_GROUP_FAILED`;
const DELETE_GROUP = 'GROUPS/DELETE_GROUP';
const DELETE_GROUP_SUCCESS = `GROUPS/DELETE_GROUP_SUCCESS`;
const DELETE_GROUP_FAILED = `GROUPS/DELETE_GROUP_FAILED`;

export {
    GET_GROUPS, SET_GROUPS, GET_GROUPS_FAILED,
    CREATE_GROUP, CREATE_GROUP_SUCCESS, CREATE_GROUP_FAILED,
    UPDATE_GROUP, UPDATE_GROUP_SUCCESS, UPDATE_GROUP_FAILED,
    DELETE_GROUP, DELETE_GROUP_SUCCESS, DELETE_GROUP_FAILED
}