const GET_TASKS = 'TASKS/GET_TASKS';
const SET_TASKS = `TASKS/SET_TASKS`;
const GET_TASKS_FAILED = `TASKS/GET_TASKS_FAILED`;
const CREATE_TASK = 'TASKS/CREATE_TASK';
const CREATE_TASK_SUCCESS = `TASKS/CREATE_TASK_SUCCESS`;
const CREATE_TASK_FAILED = `TASKS/CREATE_TASK_FAILED`;
const UPDATE_TASK = 'TASKS/UPDATE_TASK';
const UPDATE_TASK_SUCCESS = `TASKS/UPDATE_TASK_SUCCESS`;
const UPDATE_TASK_FAILED = `TASKS/UPDATE_TASK_FAILED`;
const DELETE_TASK = 'TASKS/DELETE_TASK';
const DELETE_TASK_SUCCESS = `TASKS/DELETE_TASK_SUCCESS`;
const DELETE_TASK_FAILED = `TASKS/DELETE_TASK_FAILED`;

export {
    GET_TASKS, SET_TASKS, GET_TASKS_FAILED,
    CREATE_TASK, CREATE_TASK_SUCCESS, CREATE_TASK_FAILED,
    UPDATE_TASK, UPDATE_TASK_SUCCESS, UPDATE_TASK_FAILED,
    DELETE_TASK, DELETE_TASK_SUCCESS, DELETE_TASK_FAILED
}